#!/usr/bin/bash

if [ -e /ffdl-first-boot-needed ]; then
	rm /ffdl-first-boot-needed

	# Regenerate the snakeoil certificate	
	THISHOST=$(hostnamectl hostname)
	openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
	    -keyout /etc/ssl/private/ssl-cert-snakeoil.key \
    	-out /etc/ssl/certs/ssl-cert-snakeoil.pem -subj \
		"/CN=${THISHOST}.local"
	systemctl restart apache2

	# Regenerate the Cockpit certificate
	openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout /etc/cockpit/ws-certs.d/0-self-signed.key \
        -out /etc/cockpit/ws-certs.d/0-self-signed.cert -subj \
        "/CN=${THISHOST}.local"

	# Setup FFDL
	/usr/bin/firefly-logger-loaddb
	/usr/bin/firefly-logger-takeover force-this
	systemctl enable wsjt2ffdl
	systemctl start wsjt2ffdl

	# Disable firstboot
	systemctl disable ffdl-firstboot
fi
