#!/usr/bin/env bash
# asl3/start_chroot_script
# Installs all of Firefly Logger
# Written by Jason McCormick N8EI
# GPL V3
########


# Source error handling, leave this in place
set -e

source /common.sh
install_cleanup_trap

### noninteractive Check
if [ -z "${DEBIAN_FRONTEND}" ]; then
    export DEBIAN_FRONTEND=noninteractive
fi

# usr/local
unpack filesystem/usr/local/sbin/ /usr/local/sbin/ root

## Cleanup old kernels first, minimize size and number of DKMS builds needed
/usr/local/sbin/minimize-kernels \
	$(grep VERSION_CODENAME /etc/os-release | awk 'BEGIN {FS="="};{print $2}')

## Install Firefly Logger Repo
wget -O/tmp/packetwarriors-repo.deb \
	https://repo.packetwarriors.com/packetwarriors-repo.deb
dpkg -i /tmp/packetwarriors-repo.deb
rm -f /tmp/packetwarriors-repo.deb

## Install AllStarLink Repo (for cockpit-wifimanager)
wget -O/tmp/asl-apt-repos.deb12_all.deb \
	 https://repo.allstarlink.org/public/asl-apt-repos.deb12_all.deb
	dpkg -i /tmp/asl-apt-repos.deb12_all.deb
	rm -f /tmp/asl-apt-repos.deb12_all.deb

## Do apt things
apt update
apt remove -y iptables exim4-base exim4-config exim4-daemon-light
apt autoremove -y
apt purge -y exim4-base exim4-config exim4-daemon-light
apt install -y apache2 firefly-logger-appliance vim-nox

# Create motd & issue
unpack filesystem/etc /etc
echo "" > /etc/issue
echo "" > /etc/issue.net

# Set Firstboot
unpack filesystem/etc/systemd/system/ /etc/systemd/system/ root
touch /asl3-first-boot-needed
systemctl enable systemd-time-wait-sync.service
systemctl enable ffdl-firstboot
